SELECT 
    [Extent1].[EmployeeMasterID] AS [EmployeeMasterID], 
    [Extent1].[Photo] AS [Photo], 
    [Extent1].[EmployeetName] AS [EmployeetName], 
    [Extent1].[ReportingManagerID] AS [ReportingManagerID], 
    [Extent1].[Email] AS [Email], 
    [Extent1].[EmployeePassword] AS [EmployeePassword], 
    [Extent1].[BaseLocation] AS [BaseLocation], 
    [Extent1].[Mobile] AS [Mobile], 
    [Extent1].[DesignationID] AS [DesignationID], 
    [Extent1].[RolesID] AS [RolesID], 
    [Extent1].[JoiningDate] AS [JoiningDate], 
    [Extent1].[PriorWorkExperience] AS [PriorWorkExperience], 
    [Extent1].[PAN] AS [PAN], 
    [Extent1].[Skillsid] AS [Skillsid], 
    [Extent1].[Address] AS [Address], 
    [Extent1].[PassportNo] AS [PassportNo], 
    [Extent1].[PassportExpiryDate] AS [PassportExpiryDate], 
    [Extent1].[VisaExpiryDate] AS [VisaExpiryDate], 
    [Extent1].[DateOfCreation] AS [DateOfCreation], 
    [Extent1].[DateOfModification] AS [DateOfModification], 
    [Extent1].[CreatedBy] AS [CreatedBy], 
    [Extent1].[ModifiedBy] AS [ModifiedBy], 
    [Extent1].[LastLogin] AS [LastLogin], 
    [Extent1].[isMapped] AS [isMapped]
    FROM [dbo].[CPT_ResourceMaster] AS [Extent1]